### ISSUE TITLE
ถ้าผมอยากทำให้เป็นภาษาอังกฤษ มี library รองรับไหมครับ

### ISSUE THREAD

**Issue by thapakorn604** [zapkub/react-thailand-address-typeahead#4]

**Comment by zapkub** [comment]
ยังไม่มีครับ ยังไงน่าจะแก้เปลี่ยน datasource ได้อยู่จากใน source

**Comment by zapkub** [comment]
ตอนนี้ version ใหม่สามารถ custom datasource  ได้แล้วคับ
https://zapkub.github.io/react-thailand-address-v2/?path=/docs/thailand-address-typeahead--custom-suggestion-usage#custom-datasource-usage
